# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='lastName',
            field=models.CharField(blank=True, default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
